[2025-04-15T17:59:54.773+0200] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-15T17:59:54.796+0200] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_snowflake_pipeline.dbt_tasks.dbt_debug manual__2025-04-15T15:59:46.515412+00:00 [queued]>
[2025-04-15T17:59:54.805+0200] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_snowflake_pipeline.dbt_tasks.dbt_debug manual__2025-04-15T15:59:46.515412+00:00 [queued]>
[2025-04-15T17:59:54.805+0200] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-15T17:59:54.823+0200] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): dbt_tasks.dbt_debug> on 2025-04-15 15:59:46.515412+00:00
[2025-04-15T17:59:54.832+0200] {standard_task_runner.py:72} INFO - Started process 3082 to run task
[2025-04-15T17:59:54.841+0200] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_snowflake_pipeline', 'dbt_tasks.dbt_debug', 'manual__2025-04-15T15:59:46.515412+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/dbt_snowflke_airflow.py', '--cfg-path', '/var/folders/gn/cr4yj18d1tv34pkws9v_kq1r0000gn/T/tmpve6_e23i']
[2025-04-15T17:59:54.846+0200] {standard_task_runner.py:105} INFO - Job 27: Subtask dbt_tasks.dbt_debug
[2025-04-15T17:59:54.928+0200] {task_command.py:467} INFO - Running <TaskInstance: dbt_snowflake_pipeline.dbt_tasks.dbt_debug manual__2025-04-15T15:59:46.515412+00:00 [running]> on host macbook-pro-de-user.local
[2025-04-15T17:59:55.025+0200] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_snowflake_pipeline' AIRFLOW_CTX_TASK_ID='dbt_tasks.dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2025-04-15T15:59:46.515412+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-15T15:59:46.515412+00:00'
[2025-04-15T17:59:55.028+0200] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-15T17:59:55.029+0200] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-15T17:59:55.030+0200] {logging_mixin.py:190} INFO - Current task name:dbt_tasks.dbt_debug state:running start_date:2025-04-15 15:59:54.797351+00:00
[2025-04-15T17:59:55.031+0200] {logging_mixin.py:190} INFO - Dag name:dbt_snowflake_pipeline and current dag run status:running
[2025-04-15T17:59:55.032+0200] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-15T17:59:55.035+0200] {subprocess.py:78} INFO - Tmp dir root location: /var/folders/gn/cr4yj18d1tv34pkws9v_kq1r0000gn/T
[2025-04-15T17:59:55.037+0200] {subprocess.py:88} INFO - Running command: ['/bin/bash', '-c', '/opt/venv/bin/dbt debug --project-dir /Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/snowflake']
[2025-04-15T17:59:55.048+0200] {subprocess.py:99} INFO - Output:
[2025-04-15T17:59:55.057+0200] {subprocess.py:106} INFO - /bin/bash: /opt/venv/bin/dbt: No such file or directory
[2025-04-15T17:59:55.059+0200] {subprocess.py:110} INFO - Command exited with return code 127
[2025-04-15T17:59:55.072+0200] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/airflow-env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/airflow-env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/airflow-env/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/airflow-env/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/airflow-env/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-04-15T17:59:55.089+0200] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-15T17:59:55.090+0200] {logging_mixin.py:190} INFO - Task start:2025-04-15 15:59:54.797351+00:00 end:2025-04-15 15:59:55.088641+00:00 duration:0.29129
[2025-04-15T17:59:55.091+0200] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): dbt_tasks.dbt_debug> dag:<DAG: dbt_snowflake_pipeline> dagrun:<DagRun dbt_snowflake_pipeline @ 2025-04-15 15:59:46.515412+00:00: manual__2025-04-15T15:59:46.515412+00:00, state:running, queued_at: 2025-04-15 15:59:46.554989+00:00. externally triggered: True>
[2025-04-15T17:59:55.093+0200] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 127.
[2025-04-15T17:59:55.095+0200] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_snowflake_pipeline, task_id=dbt_tasks.dbt_debug, run_id=manual__2025-04-15T15:59:46.515412+00:00, execution_date=20250415T155946, start_date=20250415T155954, end_date=20250415T155955
[2025-04-15T17:59:55.127+0200] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-15T17:59:55.136+0200] {standard_task_runner.py:124} ERROR - Failed to execute job 27 for task dbt_tasks.dbt_debug (Bash command failed. The command returned a non-zero exit code 127.; 3082)
Traceback (most recent call last):
  File "/Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/airflow-env/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/airflow-env/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/airflow-env/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/airflow-env/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/airflow-env/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/airflow-env/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/airflow-env/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/airflow-env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/airflow-env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/airflow-env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/airflow-env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/airflow-env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/airflow-env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/airflow-env/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/airflow-env/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/airflow-env/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-04-15T17:59:55.177+0200] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-15T17:59:55.213+0200] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-15T17:59:55.214+0200] {local_task_job_runner.py:245} INFO - ::endgroup::
